apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: instant-payments-secrets
  namespace: instant-payments
  labels:
    team: instant-payments
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: SecretStore
    name: azure-kv-instant-payments
  target:
    name: instant-payments-secrets
    creationPolicy: Owner
    template:
      type: Opaque
  data:
    - secretKey: BANK_API_KEY
      remoteRef:
        key: instant-payments-api-key
