apiVersion: v1
kind: Namespace
metadata:
  name: instant-payments
  labels:
    name: instant-payments
    pod-security.kubernetes.io/enforce: baseline
    pod-security.kubernetes.io/audit: baseline
    pod-security.kubernetes.io/warn: baseline
    team: instant-payments
    purpose: poc
