apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: azure-kv-instant-payments
  namespace: instant-payments
  labels:
    team: instant-payments
spec:
  provider:
    azurekv:
      authType: WorkloadIdentity
      serviceAccountRef:
        name: instant-payments-sa
      tenantId: "1de42545-e85f-4f77-9056-f5cc7c81ea5b"
      vaultUrl: "https://kv-accd-northeurope-prod.vault.azure.net"
