apiVersion: v1
kind: ServiceAccount
metadata:
  name: instant-payments-sa
  namespace: instant-payments
  labels:
    team: instant-payments
  annotations:
    azure.workload.identity/client-id: "949d5844-3049-4170-b46d-bda3dc1beffc"
