package eu.accesa.blinkpay.fips.config;

import com.fasterxml.jackson.databind.MapperFeature;
import com.fasterxml.jackson.databind.SerializationFeature;
import com.fasterxml.jackson.datatype.jdk8.Jdk8Module;
import com.fasterxml.jackson.datatype.jsr310.JavaTimeModule;
import com.fasterxml.jackson.module.jaxb.JaxbAnnotationModule;
import org.springframework.boot.autoconfigure.jackson.Jackson2ObjectMapperBuilderCustomizer;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;

/**
 * Jackson configuration to support JAXB-annotated classes from prowide-iso20022.
 *
 * The ISO 20022 model classes generated by prowide use JAXB @XmlElement annotations
 * to carry the canonical ISO 20022 field names (e.g. FIToFICstmrCdtTrf, GrpHdr).
 * Without JaxbAnnotationModule Jackson falls back to Java field names (camelCase),
 * which would break schema alignment. This config restores the standard names for
 * both serialisation and deserialisation.
 */
@Configuration
public class JacksonConfig {

    @Bean
    public Jackson2ObjectMapperBuilderCustomizer isoMessageJacksonCustomizer() {
        return builder -> builder
                .modules(new JaxbAnnotationModule(), new JavaTimeModule(), new Jdk8Module())
                .featuresToDisable(
                        SerializationFeature.WRITE_DATES_AS_TIMESTAMPS,
                        MapperFeature.USE_ANNOTATIONS   // keep false — we want JAXB annotations
                )
                .featuresToEnable(MapperFeature.USE_ANNOTATIONS);
    }
}
