package eu.accesa.blinkpay.bank.service;

import eu.accesa.blinkpay.bank.model.Transaction;
import org.springframework.stereotype.Service;
import org.springframework.web.servlet.mvc.method.annotation.SseEmitter;

import java.io.IOException;
import java.util.List;
import java.util.Map;
import java.util.concurrent.ConcurrentHashMap;
import java.util.concurrent.CopyOnWriteArrayList;

/**
 * Manages Server-Sent Event subscriptions for real-time settlement notifications.
 *
 * The registry is keyed by the ISO 11649 creditor reference generated by the
 * merchant POS and embedded in the EPC069-12 QR code (line 9). This scopes each
 * SSE stream to a single payment session, eliminating false positives when multiple
 * customers are paying concurrently at the same merchant.
 *
 * The retail app subscribes when it displays a QR code and receives the
 * "settlement" event the moment the corresponding payment is settled by FIPS.
 *
 * Multiple subscribers per reference are supported (e.g. mirrored display tabs).
 */
@Service
public class SseNotificationService {

    /** 5-minute timeout — enough for any demo transaction to complete. */
    private static final long EMITTER_TIMEOUT_MS = 5 * 60 * 1_000L;

    // creditorReference → active emitters for that payment session
    private final Map<String, CopyOnWriteArrayList<SseEmitter>> registry = new ConcurrentHashMap<>();

    /**
     * Creates and registers a new SSE emitter for the given creditor reference.
     * The caller (controller) returns this emitter directly as the response body.
     */
    public SseEmitter subscribe(String creditorReference) {
        SseEmitter emitter = new SseEmitter(EMITTER_TIMEOUT_MS);

        registry.computeIfAbsent(creditorReference, k -> new CopyOnWriteArrayList<>()).add(emitter);

        emitter.onCompletion(() -> remove(creditorReference, emitter));
        emitter.onTimeout(()    -> remove(creditorReference, emitter));
        emitter.onError(e       -> remove(creditorReference, emitter));

        return emitter;
    }

    /**
     * Pushes a "settlement" event to all subscribers watching the given creditor reference.
     * No-op if creditorReference is null (P2P payments have no waiting POS session).
     */
    public void notifySettlement(String creditorReference, Transaction tx) {
        push(creditorReference, "settlement", tx);
    }

    /**
     * Pushes a "rejection" event to all subscribers watching the given creditor reference.
     * No-op if creditorReference is null.
     */
    public void notifyRejection(String creditorReference, Transaction tx) {
        push(creditorReference, "rejection", tx);
    }

    private void push(String creditorReference, String eventName, Transaction tx) {
        if (creditorReference == null) return;

        List<SseEmitter> emitters = registry.getOrDefault(creditorReference, new CopyOnWriteArrayList<>());
        for (SseEmitter emitter : emitters) {
            try {
                emitter.send(SseEmitter.event().name(eventName).data(tx));
            } catch (IOException e) {
                emitter.completeWithError(e);
            }
        }
    }

    private void remove(String creditorReference, SseEmitter emitter) {
        CopyOnWriteArrayList<SseEmitter> list = registry.get(creditorReference);
        if (list != null) list.remove(emitter);
    }
}
