package eu.accesa.blinkpay.bank.model;

import java.math.BigDecimal;
import java.time.Instant;
import java.util.UUID;

/**
 * Immutable transaction record.
 *
 * {@code creditorReference} is the ISO 11649 structured creditor reference
 * generated by the merchant POS and embedded in the EPC069-12 QR code
 * (line 9 — structured remittance information). It scopes the SSE settlement
 * notification to the exact payment session that originated the QR code.
 * Null for P2P payments initiated without a QR code.
 */
public record Transaction(
        UUID uetr,
        String debtorIBAN,
        String creditorIBAN,
        String debtorName,
        String creditorName,
        BigDecimal amount,
        String currency,
        TransactionStatus status,
        String creditorReference,   // ISO 11649 — from QR line 9; null for P2P
        String remittanceInfo,      // unstructured — from QR line 10
        Instant createdAt,
        Instant settledAt
) {
    public static Transaction settled(UUID uetr, String debtorIBAN, String creditorIBAN,
                                      String debtorName, String creditorName,
                                      BigDecimal amount,
                                      String creditorReference, String remittanceInfo) {
        Instant now = Instant.now();
        return new Transaction(uetr, debtorIBAN, creditorIBAN, debtorName, creditorName,
                amount, "EUR", TransactionStatus.ACSC,
                creditorReference, remittanceInfo, now, now);
    }

    public static Transaction rejected(UUID uetr, String debtorIBAN, String creditorIBAN,
                                       String debtorName, String creditorName,
                                       BigDecimal amount,
                                       String creditorReference, String remittanceInfo) {
        Instant now = Instant.now();
        return new Transaction(uetr, debtorIBAN, creditorIBAN, debtorName, creditorName,
                amount, "EUR", TransactionStatus.RJCT,
                creditorReference, remittanceInfo, now, null);
    }
}
